name: m0-lockfile

on:
  push:
    branches:
      - "m0/**"

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate lockfile
        run: cargo generate-lockfile
      - uses: actions/upload-artifact@v4
        with:
          name: cargo-lock
          path: Cargo.lock
